//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using VeXe.Models;

public partial class vexeEntities1 : DbContext
{
    public vexeEntities1()
        : base("name=vexeEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Ghe> Ghes { get; set; }
    public virtual DbSet<Khachhang> Khachhangs { get; set; }
    public virtual DbSet<Lotrinh> Lotrinhs { get; set; }
    public virtual DbSet<Taikhoan> Taikhoans { get; set; }
    public virtual DbSet<Tuyen> Tuyens { get; set; }
    public virtual DbSet<Ve> Ves { get; set; }
    public virtual DbSet<Xe> Xes { get; set; }
}
